//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballTicketOffice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public int ClientId { get; set; }
        public int Sector { get; set; }
        public int Row { get; set; }
        public int Site { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int MatchId { get; set; }
        public int CashierId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
